//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessright_Right
    {
        public int Id { get; set; }
        public int AccessrightId { get; set; }
        public int AccessType { get; set; }
        public int AccessTypeRight { get; set; }
    
        public virtual Accessright Accessright { get; set; }
        public virtual Accessright Accessright1 { get; set; }
    }
}
