//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Core.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CoreModel : DbContext
    {
        public CoreModel()
            : base("name=CoreModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessright> Accessright { get; set; }
        public virtual DbSet<Accessright_Right> Accessright_Right { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Account_Information> Account_Information { get; set; }
        public virtual DbSet<Account_Information_Generic> Account_Information_Generic { get; set; }
        public virtual DbSet<Account_Information_Generic_Value> Account_Information_Generic_Value { get; set; }
        public virtual DbSet<Account_Session> Account_Session { get; set; }
        public virtual DbSet<AccountAccess> AccountAccess { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<ClubLinkModule> ClubLinkModule { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<GenericFile> GenericFile { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<LoginLog> LoginLog { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<ModuleLink> ModuleLink { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<Search> Search { get; set; }
        public virtual DbSet<TECHNICS> TECHNICS { get; set; }
        public virtual DbSet<GenericItemPermission> GenericItemPermission { get; set; }
    
        public virtual ObjectResult<GetActiveAccountSessions_Result> GetActiveAccountSessions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetActiveAccountSessions_Result>("GetActiveAccountSessions");
        }
    }
}
