//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericItemPermission
    {
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int ObjectType { get; set; }
        public int ObjectId { get; set; }
        public Nullable<int> AccessrightId { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual Accessright Accessright { get; set; }
        public virtual Account Account { get; set; }
        public virtual Club Club { get; set; }
    }
}
