//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericFile
    {
        public int Id { get; set; }
        public int FileType { get; set; }
        public int ModuleType { get; set; }
        public int ObjectId { get; set; }
        public string Path { get; set; }
        public string FileExtension { get; set; }
    }
}
