//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleLink
    {
        public int Id { get; set; }
        public int ModuleId { get; set; }
        public string Sref { get; set; }
        public string Text { get; set; }
        public int AccessType { get; set; }
        public int AccessTypeRight { get; set; }
        public bool IsAdminLink { get; set; }
        public Nullable<int> SpecificClubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Module Module { get; set; }
        public virtual Module Module1 { get; set; }
    }
}
