//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Newsletter.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter_Send_Item
    {
        public int Id { get; set; }
        public int NewsletterSendId { get; set; }
        public Nullable<int> SendToUserId { get; set; }
        public bool IsSent { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime SendDate { get; set; }
        public System.DateTime ReadDate { get; set; }
        public string Email { get; set; }
        public string NewsletterSendItemGUID { get; set; }
        public Nullable<int> SendToContactId { get; set; }
        public bool HasUnsubscribed { get; set; }
        public string SendType { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Newsletter_Send Newsletter_Send { get; set; }
    }
}
