//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Newsletter.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Vicdude_NewsletterEntities : DbContext
    {
        public Vicdude_NewsletterEntities()
            : base("name=Vicdude_NewsletterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Newsletter_Send> Newsletter_Send { get; set; }
        public virtual DbSet<Newsletter_Send_Item> Newsletter_Send_Item { get; set; }
        public virtual DbSet<Newsletters> Newsletters { get; set; }
    
        public virtual ObjectResult<GetNewsletterStatsByNewsletterId_Result> GetNewsletterStatsByNewsletterId(Nullable<int> newsletterId, Nullable<int> clubId)
        {
            var newsletterIdParameter = newsletterId.HasValue ?
                new ObjectParameter("NewsletterId", newsletterId) :
                new ObjectParameter("NewsletterId", typeof(int));
    
            var clubIdParameter = clubId.HasValue ?
                new ObjectParameter("ClubId", clubId) :
                new ObjectParameter("ClubId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetNewsletterStatsByNewsletterId_Result>("GetNewsletterStatsByNewsletterId", newsletterIdParameter, clubIdParameter);
        }
    }
}
