//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Mediabank.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediabankFile
    {
        public int Id { get; set; }
        public int ClubId { get; set; }
        public int CreatedBy { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FileUrl { get; set; }
        public string Thumbnail { get; set; }
        public string FileType { get; set; }
        public string FileExtension { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool LimitFileAccess { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Club Club { get; set; }
    }
}
