//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Forms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormFields
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormFields()
        {
            this.FormExternalSubmitValues = new HashSet<FormExternalSubmitValues>();
            this.FormFieldsOptions = new HashSet<FormFieldsOptions>();
            this.FormSubmitValues = new HashSet<FormSubmitValues>();
            this.FormSubmitValues1 = new HashSet<FormSubmitValues>();
        }
    
        public int Id { get; set; }
        public int FormId { get; set; }
        public string ClassName { get; set; }
        public string Type { get; set; }
        public string Label { get; set; }
        public bool IsRequired { get; set; }
        public bool CanMultiply { get; set; }
    
        public virtual Form Form { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormExternalSubmitValues> FormExternalSubmitValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormFieldsOptions> FormFieldsOptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSubmitValues> FormSubmitValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSubmitValues> FormSubmitValues1 { get; set; }
    }
}
