//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Forms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSubmitValues
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ClubId { get; set; }
        public int FormId { get; set; }
        public string Value { get; set; }
        public int FormFieldId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Form Form1 { get; set; }
        public virtual FormFields FormFields { get; set; }
        public virtual FormFields FormFields1 { get; set; }
        public virtual Account Account { get; set; }
        public virtual Club Club { get; set; }
    }
}
