//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Forms.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormsEntities : DbContext
    {
        public FormsEntities()
            : base("name=FormsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Form> Form { get; set; }
        public virtual DbSet<Form_Emails> Form_Emails { get; set; }
        public virtual DbSet<FormExternalSubmitValues> FormExternalSubmitValues { get; set; }
        public virtual DbSet<FormFields> FormFields { get; set; }
        public virtual DbSet<FormFieldsOptions> FormFieldsOptions { get; set; }
        public virtual DbSet<FormSubmitValues> FormSubmitValues { get; set; }
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Club> Club { get; set; }
    }
}
