//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SW.Forms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Emails
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public string Email { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Form Form1 { get; set; }
    }
}
